### ISSUE TITLE
ExtensionReferenceFilter over-zealously detects "extensions" in the middle of a path

### ISSUE THREAD

**Issue by niels** [Norconex/collector-core#2]
[The current implementation of `acceptReference`](https://github.com/Norconex/collector-core/blob/master/norconex-collector-core/src/main/java/com/norconex/collector/core/filter/impl/ExtensionReferenceFilter.java#L89) will consider the last string following the last dot _anywhere in the path_ (or perhaps even the full URL?) to be the file extension.

E.g. given a URL such as https://herimedia.com/norconex-test/this.is.not.a.file/test, the file extension is detected to be `file/test`.

I believe the correct implementation would only try to find a file extension within the last path segment, e.g. only within `test`.

If not one else claims this ticket, I will try to submit a patch late next week. As such, this serves as a reminder to myself :)

**Comment by niels** [comment]
FYI, I just verified that the "extension" is indeed looked for in the entire URL, including the host.

For example, if one wanted to block `.com` _files_, one would actually often also block `.com` _domains_ (unless the path following that domain included a dot).

**Comment by niels** [comment]
Fixed in #4.

**Comment by essiembre** [comment]
I modified it slightly to better support non-URL references.  Collector Core library being generic (not specific to the web).

Thanks for your contribution!
