### ISSUE TITLE
[JobSuite] Implementing IJobLifeCycleListener requires MutableJobStatus

### ISSUE THREAD

**Issue by sylvainroussy** [Norconex/collector-core#8]
Hi!
I have a class wich implements _IJobLifeCycleListener_.

However, when an event is fired by the JobSuite an exception like the following is launched :

`Caused by: java.lang.NoSuchMethodException: No such accessible method: jobProgressed()`

The cause is the use of (in _fire ()_ method of _JobSuite_):
`MethodUtils.invokeExactMethod(l, methodName, argument);`
The argument here is a MutableJobStatus instead of IJobStatus declared in the _IJobLifeCycleListener_
 interface then the exception occured.

Duplicating all _IJobLifeCycleListener_ interface methods in my implementation from:
`public void jobStarted(IJobStatus status)`
with
`public void jobStarted(MutableJobStatus status)`
works.

Is this really a prerequisite to call an **invokeExactMethod()** here ?

[edit : renaming IJobStatus interface by IJobLifeCycleListener interface ]

**Comment by essiembre** [comment]
This is fixed in a new [JEF API snapshot release](https://www.norconex.com/jef/api/download).  Please confirm.

Norconex Collector Core/HTTP/Filesystem snapshot version were also all updated to contain this latest JEF API fix.

**Comment by sylvainroussy** [comment]
Fixed!
