### ISSUE TITLE
Support MongoDB SCRAM-SHA-1 authentication mechanism, as well as CR

### ISSUE THREAD

**Issue by danizen** [Norconex/collector-core#9]
Paul,

Finally - a clear bug/feature request.    Our mongodb installation is version 3.2.10, and thus its default authentication mechanism is SCRAM-SHA-1.   In the `buildMongoDB` static method, `com.norconex.collector.core.data.store.impl.mongo.MongoCrawlDataStore` calls `MongoCredential.createMongoCRCredential` to create the older authentication mechanism.

I'll probably implement this and contribute back, but if you get there first, no problems.

**Comment by essiembre** [comment]
I merged your pull-request https://github.com/Norconex/collector-core/pull/10.  I also took the time to upgrade the MongoDB related code to use the 3.x API classes instead.  I made a new [snapshot release](https://www.norconex.com/collectors/collector-http/download) of the HTTP Collector that uses the new collector core version with your credential additions. 

Why all was good in my own tests, I would appreciate if you can confirm this new version works for you.

**Comment by danizen** [comment]
I will check and let you know.

**Comment by danizen** [comment]
Works for me with a download of 2.7.1-SNAPSHOT.   I see that it contains `norconex-collector-core-1.8.1-SNAPSHOT`, and that this is also published to oss.sonatype.org snapshots.

**Comment by essiembre** [comment]
Thanks for confirming.
